### ISSUE TITLE
Rename to `mongodb-study`

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/mongodb-study#2]
Make it seem less task oriented and more overview/context oreiented

**Comment by jrhorn424** [comment]
:+1:

**Comment by RealWeeks** [comment]
@gaand @jrhorn424 renamed. Calendar already reflects this change.

**Comment by gaand** [comment]
@J-Weeks does waffle?

**Comment by RealWeeks** [comment]
yes
