### ISSUE TITLE
Remove mongodb webscale (bro) video?

### ISSUE THREAD

**Issue by RealWeeks** [ga-wdi-boston/mongodb-study#3]
Included in sql intro (this time didn't show but it is referenced in the repo).  Show during mongodb-crud?

**Comment by gaand** [comment]
@J-Weeks I think have them watch it in the study.  Then it doesn't take class time.  But ask a question that can only be answered by the video.

**Comment by MicFin** [comment]
The video seems to align with the 2nd objective `Comprehend the fanboy nature of MongoDB`.  For cohort 016, we added the question 

>Why is MongoDB so popular?  Explain why popularity should not be the only factor when choosing a technology

The video covers a few reasons why the common reasons MongoDB is "popular" are not the only factors that should be considered.
