### ISSUE TITLE
Change prerequisite to sql-nosql-study?

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/mongodb-study#4]
Or did we calendar this incorrectly?

This study on Friday, discussion on Monday.

**Comment by neugierige** [comment]
@gaand is this still an issue? the latest update to this repo (October, by Brian) did not address this. 

And when you say "change," do you mean to remove the 2 existing prerequisites and replace with the sql-nosql-study? Or to replace 1 of them with the sql-nosql-study? Or to add it in addition to the existing?

**Comment by MicFin** [comment]
This appears to be correct for cohort 016 as we present the lesson on 2/27 and list prereqs `node-api` which we present on 2/24 and `sql-nosql-study` which we present on 2/23.
