### ISSUE TITLE
Have developers install mongodb as part of study.

### ISSUE THREAD

**Issue by gaand** [ga-wdi-boston/mongodb-study#5]
This seems sensible if we don't get to it in installfest.

**Comment by neugierige** [comment]
@gaand what is GA's preferred way of installing mongodb? should they follow [the instructions](https://docs.mongodb.com/getting-started/shell/installation/) on the mongodb documentation?

**Comment by gaand** [comment]
`brew install mongodb`

**Comment by MicFin** [comment]
This was previously added in the README but the README did not fit the current `study-template` for cohort 016 so this step has been moved to `study.md`.
